#!/bin/bash

echo "=== NOBS Weather Widget Setup Instructions ==="
echo ""
echo "To complete the widget setup, you need to configure App Groups in Xcode:"
echo ""
echo "1. Open your project in Xcode"
echo "2. Select your main app target (nobsweather)"
echo "3. Go to 'Signing & Capabilities' tab"
echo "4. Click '+ Capability' and add 'App Groups'"
echo "5. Create/enable the app group: group.com.anonymous.nobs.weather"
echo ""
echo "6. Select your widget target (nobs-widget)"
echo "7. Go to 'Signing & Capabilities' tab"
echo "8. Click '+ Capability' and add 'App Groups'"
echo "9. Enable the same app group: group.com.anonymous.nobs.weather"
echo ""
echo "10. Add the native module files to your Xcode project:"
echo "    - RNUserDefaults.h"
echo "    - RNUserDefaults.m"
echo ""
echo "11. Clean and rebuild your project"
echo ""
echo "=== Important Notes ==="
echo "• This widget is designed for LOCK SCREEN only (accessory widgets)"
echo "• Do NOT try to add it to home screen - it only supports lock screen sizes"
echo "• If you get 'systemMedium not supported' error, ignore it - that's expected"
echo ""
echo "=== Widget Features ==="
echo "• Shows current temperature and UV index for pinned cities"
echo "• Supports lock screen widgets (inline, circular, rectangular)"
echo "• Updates every 15 minutes"
echo "• Data is shared between main app and widget via App Groups"
echo ""
echo "=== Usage ==="
echo "1. Pin a city in the main app"
echo "2. Go to your iPhone lock screen"
echo "3. Long press the lock screen and tap 'Customize'"
echo "4. Add widgets and select 'NOBS Weather'"
echo "5. Choose from 3 sizes: Inline, Circular, or Rectangular"
echo "6. The widget will display the pinned city's weather data"
